name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-app:latest

      - name: Test SSH connection
        run: ssh -vvv -i ~/.ssh/id_rsa ubuntu@ec2-3-6-201-69.ap-south-1.compute.amazonaws.com "echo SSH connection successful"

      - name: Pull Docker image on server
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@ec2-3-6-201-69.ap-south-1.compute.amazonaws.com "docker pull ${{ secrets.DOCKER_USERNAME }}/my-app:latest"

      - name: Stop running Docker container
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@ec2-3-6-201-69.ap-south-1.compute.amazonaws.com "docker stop my-app || true"

      - name: Remove stopped Docker container
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@ec2-3-6-201-69.ap-south-1.compute.amazonaws.com "docker rm my-app || true"

      - name: Run new Docker container
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@ec2-3-6-201-69.ap-south-1.compute.amazonaws.com "docker run -d --name my-app -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/my-app:latest"
