name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-app:latest

      - name: Create SSH key file
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Test SSH connection
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          ssh -vvv -i ec2_key.pem -o StrictHostKeyChecking=no -o BatchMode=yes -o ConnectTimeout=60 $EC2_USER@$EC2_HOST "echo SSH connection successful"

      - name: Pull Docker image on server
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          ssh -i ec2_key.pem -o StrictHostKeyChecking=no -o BatchMode=yes -o ConnectTimeout=60 $EC2_USER@$EC2_HOST "docker pull ${{ secrets.DOCKER_USERNAME }}/my-app:latest"

      - name: Stop running Docker container
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          ssh -i ec2_key.pem -o StrictHostKeyChecking=no -o BatchMode=yes -o ConnectTimeout=60 $EC2_USER@$EC2_HOST "docker stop my-app || true"

      - name: Remove stopped Docker container
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          ssh -i ec2_key.pem -o StrictHostKeyChecking=no -o BatchMode=yes -o ConnectTimeout=60 $EC2_USER@$EC2_HOST "docker rm my-app || true"

      - name: Run new Docker container
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          ssh -i ec2_key.pem -o StrictHostKeyChecking=no -o BatchMode=yes -o ConnectTimeout=60 $EC2_USER@$EC2_HOST "docker run -d --name my-app -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/my-app:latest"
