name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ec2-3-6-201-69.ap-south-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: ssh -i ~/.ssh/id_rsa ubuntu@ec2-3-6-201-69.ap-south-1.compute.amazonaws.com "echo SSH connection successful"
